kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  storageClassName: ""
  volumeName: example-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 1Gi
