apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # limits
      cpu: 500m
    defaultRequest: # requests
      cpu: 200m
    max:
      cpu: 1000m
    min:
      cpu: 100m
    type: Container
  - max: 
      storage: 2Gi
    type: PersistentVolumeClaim

