apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # limits
      cpu: 200m
      memory: 500Mi
    defaultRequest: # requests
      cpu: 100m
      memory: 300Mi
    max:
      cpu: 1000m
      memory: 1Gi
    min:
      cpu: 10m
      memory: 10Mi
    type: Container
  - max: 
      storage: 2Gi
    type: PersistentVolumeClaim

