apiVersion: v1
kind: Pod
metadata:
  name: brokenPod
  labels:
    run: brokenPod
spec:
  volumes:
  - name: foobar
    emptyDir: {}
    terminationGracePeriodSeconds: 0
  containers:
  - image: nginx
    name: nginx-server
    resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 10m 
      memory: 10Mi
    ports:
      containerPort: 80