apiVersion: batch/v1
kind: Job
metadata:
  name: somejob
spec:
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
      - image: busybox
        name: somejob
        args:
          - /bin/sh
          - -c
          - 'echo "-- STARTING --"; sleep 30; echo "-- COMPLETE --"'
      restartPolicy: Never
